version: 2

updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Ignore auto-updates on SemVer major releases
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: pip
    directory: "/reqs"
    schedule:
      interval: weekly
    ignore:
      # Ignore auto-updates on SemVer major releases
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Ignore auto-updates on pytz (they must be updated together)
      - dependency-name: "pytz"
      - dependency-name: "types-pytz"
    allow:
      - dependency-type: development
      - dependency-type: production
